### PR TITLE
Modified and improved test suite

### PR DESCRIPTION
**Pull request by daniellivingston**
Test suite has been changed in a number of ways:

1. Duplicated control files present in each `level` dir (`control01.py`,`run_test.py`,`check_test.py`) have been replaced with a central testing library in `test/lg_test_lib/`. This should be easier to maintain.

2. Comments, whitespace, and banners are now ignored (see `test/lg_test_lib/check_test.py:remove_junk_from_filestream()`).

3. `suite.py` has been simplified

4. outx3dgen files fixed (outdated: `test/level02/exodus_prisms/reference/outx3dgen`, missing: `test/level01/hextotet/reference/outx3dgen`)

### CODE REVIEW

**Comment by daniellivingston** [comment]
Updated output (note - `No lines differ`!):

```
37 Check Directory ./triangulate_polygon --------------------------

No lines differ.
37 Done with Directory ./triangulate_polygon -----------------------

38 Check Directory ./write_exo --------------------------

No lines differ.
38 Done with Directory ./write_exo -----------------------

39 Check Directory ./zone_outside --------------------------

No lines differ.
39 Done with Directory ./zone_outside -----------------------

40 Check Directory ./zone_outside_minmax --------------------------

No lines differ.
40 Done with Directory ./zone_outside_minmax -----------------------

All 40 successful!
Check done.
Full result written to:

/Users/livingston/playground/new-test-suite/test/level01/diffout_mac.txt

and copied to ./test_results
```

**Comment by daniellivingston** [comment]
@millerta Do we still need these files?

```
❯ ls test/level*/*.scr
test/level01/clean_testdirs.scr test/level02/clean_testdirs.scr
```

**Comment by daniellivingston** [comment]
The following directories failed, due to changed logging text:

```
./smooth_massage
./intrp_2D_sizes
./interp_voronoi
./interp_map
./interp_continuous
```

Fixed in 2d63df5ed5cd48bc8b0f5b144de79c701174a425..

**Comment by millerta** [comment]
the test suite is not parsing arguments correctly.
the test suite is not reporting differences that are found with simple diff outx3dgen reference/outx3dgen

Erica is fixing these issues for the new release.

**Pull request merged**
